-- Outbound notification agents (internal/notifyagents, migration 00029).
-- secret is ciphertext; only the notifyagents store decrypts it.

-- name: ListNotificationAgents :many
SELECT id, kind, name, enabled, events, config, secret, allow_private_network,
       last_success_at, last_error, last_error_at, created_at, updated_at
FROM notification_agents
ORDER BY created_at, id;

-- name: GetNotificationAgent :one
SELECT id, kind, name, enabled, events, config, secret, allow_private_network,
       last_success_at, last_error, last_error_at, created_at, updated_at
FROM notification_agents
WHERE id = $1;

-- name: ListEnabledNotificationAgentsForEvent :many
SELECT id, kind, name, enabled, events, config, secret, allow_private_network,
       last_success_at, last_error, last_error_at, created_at, updated_at
FROM notification_agents
WHERE enabled AND sqlc.arg(event)::text = ANY(events)
ORDER BY created_at, id;

-- name: CreateNotificationAgent :one
-- id is generated by the caller: the secret is encrypted bound to the row id,
-- so the id must be known before the INSERT.
INSERT INTO notification_agents (id, kind, name, enabled, events, config, secret, allow_private_network)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, kind, name, enabled, events, config, secret, allow_private_network,
          last_success_at, last_error, last_error_at, created_at, updated_at;

-- name: UpdateNotificationAgent :one
-- Full replace of the editable fields; the caller merges the PATCH onto the
-- current row (a kept secret is passed back as the stored ciphertext). kind is
-- immutable.
UPDATE notification_agents
SET name                  = $2,
    enabled               = $3,
    events                = $4,
    config                = $5,
    secret                = $6,
    allow_private_network = $7,
    updated_at            = now()
WHERE id = $1
RETURNING id, kind, name, enabled, events, config, secret, allow_private_network,
          last_success_at, last_error, last_error_at, created_at, updated_at;

-- name: DeleteNotificationAgent :execrows
DELETE FROM notification_agents WHERE id = $1;

-- name: RecordNotificationAgentSuccess :exec
UPDATE notification_agents SET last_success_at = now() WHERE id = $1;

-- name: RecordNotificationAgentFailure :exec
UPDATE notification_agents
SET last_error = sqlc.arg(last_error)::text, last_error_at = now()
WHERE id = $1;

-- name: ListNewContentForNotificationAgents :many
-- The batched "new content" message: titles added to one PUBLIC library after
-- the watermark, newest first. Episodes carry their show (episode → season →
-- show) so the message can say "Show — 3 new episodes". Seasons, tracks,
-- photos and chapters are left out: their parent (show, album, book) is the
-- title worth announcing. Private libraries return nothing — the agent
-- channels are shared (a household group chat), and announcing titles from a
-- library some members can't see leaks it, the reason scan_complete notices
-- are scoped to a library's viewers.
SELECT m.id, m.type, m.title, m.year, m.created_at,
       sh.id AS show_id, sh.title AS show_title
FROM media_items m
JOIN libraries l ON l.id = m.library_id AND NOT l.is_private AND l.deleted_at IS NULL
LEFT JOIN media_items se ON m.type = 'episode' AND se.id = m.parent_id
LEFT JOIN media_items sh ON sh.id = se.parent_id AND sh.deleted_at IS NULL
WHERE m.library_id = sqlc.arg(library_id)
  AND m.created_at > sqlc.arg(since)
  AND m.deleted_at IS NULL
  AND m.type = ANY (ARRAY['movie', 'show', 'episode', 'album', 'audiobook', 'book',
                          'podcast', 'music_video', 'home_video']::text[])
ORDER BY m.created_at DESC, m.id
LIMIT sqlc.arg(max_rows);
