# Post-install: initialise Postgres, build .env, write WinSW XMLs, register services.
#
# Called from Inno Setup's [Run] section with -InstallDir pointing at the
# install location. Must succeed in one pass — failures roll back the
# whole install.

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$InstallDir
)

$ErrorActionPreference = "Stop"
$dataRoot = "$env:ProgramData\OnScreen"
$pgdata   = "$dataRoot\pgdata"
$logs     = "$dataRoot\logs"
$envFile  = "$InstallDir\.env"

New-Item -ItemType Directory -Path $dataRoot, $logs -Force | Out-Null

function Write-Log {
    param([string]$Msg)
    Add-Content -Path "$logs\install.log" -Value "$(Get-Date -Format o)  $Msg"
    Write-Host $Msg
}

# Random password / secret. PostgreSQL needs an ASCII-printable password
# without URL-special chars (we put it in DATABASE_URL); SECRET_KEY needs
# 32+ bytes of entropy. Use base64-of-random-bytes for both, stripped of
# +/= to keep the URL shape simple.
function New-Secret {
    param([int]$Bytes = 24)
    $b = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
    [Convert]::ToBase64String($b) -replace '[+/=]',''
}

# ── 1. Initialize Postgres cluster (skip if already initdb'd by a
#       previous install on the same machine — re-running the installer
#       must be idempotent so users can repair without losing data). ──
$pgInitMarker = "$pgdata\PG_VERSION"
if (-not (Test-Path $pgInitMarker)) {
    Write-Log "Postgres: initdb $pgdata"
    if (Test-Path $pgdata) { Remove-Item -Recurse -Force $pgdata }
    New-Item -ItemType Directory -Path $pgdata -Force | Out-Null

    # Password file fed to initdb so the postgres superuser gets a known
    # value we can put in DATABASE_URL. The file is deleted right after
    # initdb consumes it.
    $pgPassword = New-Secret 24
    $pwFile = Join-Path $env:TEMP "onscreen-pg-pw.txt"
    [System.IO.File]::WriteAllText($pwFile, $pgPassword, [System.Text.Encoding]::ASCII)

    $initdb = "$InstallDir\pgsql\bin\initdb.exe"
    & $initdb -D $pgdata -U postgres --pwfile $pwFile -E UTF8 --locale=C 2>&1 |
        ForEach-Object { Write-Log "  initdb: $_" }
    if ($LASTEXITCODE -ne 0) { throw "initdb failed (exit $LASTEXITCODE)" }
    Remove-Item -Force $pwFile

    # Pin Postgres to localhost-only so the service isn't accessible
    # from the LAN — single-user laptop / desktop deploy, no need for
    # remote access. Default postgresql.conf binds only to 127.0.0.1
    # because listen_addresses defaults to localhost; we just confirm
    # nobody has changed it. pg_hba.conf default permits scram-sha-256
    # for the postgres role over localhost which is what we want.
    $confPath = "$pgdata\postgresql.conf"
    (Get-Content $confPath) -replace "^#?\s*port\s*=.*", "port = 5432" |
        Set-Content -Encoding ASCII $confPath
} else {
    Write-Log "Postgres: cluster already initialised; skipping initdb"
    # Read the password we generated last time. Stored next to the env
    # file so we can re-derive DATABASE_URL on a repair-install.
    if (Test-Path $envFile) {
        $existing = Get-Content $envFile | Where-Object { $_ -match '^DATABASE_URL=' }
        if ($existing -and $existing -match 'postgres://postgres:([^@]+)@') {
            $pgPassword = [uri]::UnescapeDataString($Matches[1])
        }
    }
    if (-not $pgPassword) {
        throw "Existing Postgres cluster found but no recoverable password in .env; cannot proceed safely"
    }
}

# ── 2. Start Postgres briefly to create the onscreen database (only on
#       fresh installs — repair runs reuse the existing DB). ──
if (-not (Test-Path "$dataRoot\.db-bootstrapped")) {
    Write-Log "Postgres: starting one-shot for bootstrap"
    $pgctl = "$InstallDir\pgsql\bin\pg_ctl.exe"
    & $pgctl -D $pgdata -l "$logs\pg-bootstrap.log" -w start 2>&1 |
        ForEach-Object { Write-Log "  pg_ctl start: $_" }
    if ($LASTEXITCODE -ne 0) { throw "pg_ctl start failed (exit $LASTEXITCODE)" }
    try {
        $env:PGPASSWORD = $pgPassword
        $psql = "$InstallDir\pgsql\bin\psql.exe"
        & $psql -h localhost -U postgres -tAc "CREATE DATABASE onscreen;" 2>&1 |
            ForEach-Object { Write-Log "  psql: $_" }
        if ($LASTEXITCODE -ne 0) { throw "CREATE DATABASE failed" }
        New-Item -ItemType File -Path "$dataRoot\.db-bootstrapped" -Force | Out-Null
    } finally {
        & $pgctl -D $pgdata -m fast -w stop 2>&1 |
            ForEach-Object { Write-Log "  pg_ctl stop: $_" }
        $env:PGPASSWORD = $null
    }
}

# ── 3. Generate .env (only on fresh install) ──
if (-not (Test-Path $envFile)) {
    $secretKey = New-Secret 32
    $pgUrl = "postgres://postgres:$([uri]::EscapeDataString($pgPassword))@localhost:5432/onscreen?sslmode=disable"
    @"
# Auto-generated by OnScreen installer. Edit if you know what you're doing —
# DATABASE_URL's password matches the bundled Postgres cluster's `postgres`
# role; changing it here without rotating in the database will break startup.
DATABASE_URL="$pgUrl"
VALKEY_URL="redis://localhost:6379"
SECRET_KEY="$secretKey"
LOG_LEVEL="info"
"@ | Set-Content -Encoding utf8 $envFile
    Write-Log ".env written"
} else {
    Write-Log ".env already present; preserved"
}

# ── 4. Rewrite service-onscreen.xml to inject the .env contents as
#       <env/> tags (so the service inherits the same config the
#       binary would see if launched from a shell). ──
$xmlPath = "$InstallDir\service-onscreen.xml"
$xml = Get-Content $xmlPath -Raw
$envLines = @('  <env name="PATH" value="{app}\ffmpeg;%PATH%"/>'.Replace('{app}', $InstallDir))
Get-Content $envFile | ForEach-Object {
    if ($_ -match '^\s*(?:export\s+)?(\w+)\s*=\s*["'']?(.*?)["'']?\s*$') {
        $key = $Matches[1]; $val = $Matches[2]
        if ($key -and $key -notmatch '^\s*#' -and $key -ne "PATH") {
            $val = $val -replace '&','&amp;' -replace '<','&lt;' -replace '>','&gt;' -replace '"','&quot;'
            $envLines += "  <env name=`"$key`" value=`"$val`"/>"
        }
    }
}
$xml = $xml -replace '(?ms)\s*<env\s[^/]*/>', ''
$envBlock = ($envLines -join "`n")
$xml = $xml -replace '</service>', "`n$envBlock`n</service>"
# Replace remaining {app} / {userpf} placeholders with the real paths.
$xml = $xml -replace '\{app\}', [regex]::Escape($InstallDir).Replace('\','\\')
$xml = $xml -replace '\{userpf\}', [regex]::Escape($env:ProgramData).Replace('\','\\')
# The escape above is for regex; for an XML attribute we want raw paths.
$xml = $xml -replace [regex]::Escape($InstallDir).Replace('\','\\\\'), $InstallDir
Set-Content -Path $xmlPath -Value $xml -Encoding utf8

# Also expand placeholders in the other two service XMLs.
foreach ($svc in @("service-postgres.xml", "service-redis.xml")) {
    $p = Join-Path $InstallDir $svc
    (Get-Content $p -Raw) `
        -replace '\{app\}', $InstallDir `
        -replace '\{userpf\}', $env:ProgramData `
        | Set-Content -Path $p -Encoding utf8
}

# ── 5. Register and start all three services. ──
function Register-WinswService {
    param([string]$XmlName)
    $xmlFull = "$InstallDir\$XmlName"
    Write-Log "Registering service from $XmlName"
    & "$InstallDir\WinSW.exe" install $xmlFull 2>&1 | ForEach-Object { Write-Log "  $_" }
    if ($LASTEXITCODE -ne 0) { throw "$XmlName install failed (exit $LASTEXITCODE)" }
    & "$InstallDir\WinSW.exe" start $xmlFull 2>&1 | ForEach-Object { Write-Log "  $_" }
    if ($LASTEXITCODE -ne 0) { throw "$XmlName start failed (exit $LASTEXITCODE)" }
}

# Postgres + Redis must register first (OnScreen depends on them via
# <depend/> tags; SCM rejects starting a service whose deps aren't
# registered yet).
Register-WinswService "service-postgres.xml"
Register-WinswService "service-redis.xml"
Register-WinswService "service-onscreen.xml"

Write-Log "All services up. Open http://localhost:7070 for setup."
